List<String> botNames = [
  "Ayoub", "Youssef", "Rachid", "Hamza", "Mehdi", "Amine", "Anas", "Omar", "Said", "Khalid",
  "Soufiane", "Mohamed", "Abdel", "Adil", "Nabil", "Ilyas", "Hicham", "Mouad", "Taha", "Imad",
  "Fatima", "Zahra", "Khadija", "Salma", "Nora", "Lina", "Sara", "Aicha", "Meriem", "Yasmina",
  "Ikram", "Hajar", "Sanaa", "Rania", "Naima", "Asmae", "Malak", "Wafaa", "Hanane", "Oumaima",
  "Souad", "Ilham", "Rim", "Amal", "Aya", "Laila", "Salima", "Najwa", "Samira", "Jamila",
  "Yassine", "Reda", "Ayham", "Bilal", "Mouhammad", "Karim", "Zakaria", "Hassan", "Abdelhak",
  "Abdelkader", "Badr", "Fouad", "Ismail", "Adnane", "Saad", "Majid", "Jamal", "Mohannad", "Rayan",
  "Imane", "Chaimae", "Soukaina", "Asma", "Mouna", "Nada", "Rachida", "Najat", "Latifa", "Zineb",
  "Hind", "Saloua", "Samia", "Abir", "Yasmine", "Oumaima", "Siham", "Ghita", "Fadoua", "Safae",
  "Marwa", "Rita", "Dounia", "Nour", "Ilham", "Ikram", "Sofia", "Meryem", "Hanae", "Kenza",
  "Aniss", "Ayham", "Aymane", "Othman", "Mouhsine", "Rida", "Fayçal", "Hamada", "Amin", "Ibrahim",
  "Amar", "Younes", "Tarik", "Fouzia", "Khouloud", "Samira", "Bouchra", "Nisrine", "Imen", "Dina",
  "Mounia", "Sofia", "Malak", "Sanae", "Siham", "Wissal", "Chaymae", "Rachida", "Nadia", "Asmaa",
  "Fadwa", "Aya", "Rita", "Nada", "Hanane", "Salima", "Nawal", "Yassine", "Reda", "Hassan", "Hamza",
  "Mehdi", "Mohamed", "Adil", "Nabil", "Ilyas", "Hicham", "Mouad", "Taha", "Imad", "Abdel",
  "Ayoub", "Omar", "Said", "Karim", "Zakaria", "Bilal", "Anas", "Majid", "Jamal", "Saad",
  "Abdelhak", "Fouad", "Ismail", "Adnane", "Rayan", "Mouhsine", "Othman", "Amine", "Ibrahim", "Tarik",
  "Ayham", "Aymane", "Hamid", "Hamada", "Younes", "Amar", "Fayçal", "Nour", "Sofia", "Rania",
  "Malak", "Hanae", "Kenza", "Oumaima", "Dounia", "Meryem", "Ikram", "Ghita", "Rim", "Fatima",
  "Zahra", "Khadija", "Salma", "Nora", "Lina", "Sara", "Aicha", "Meriem", "Yasmina", "Ikram",
  "Hajar", "Sanaa", "Naima", "Asmae", "Wafaa", "Hanane", "Souad", "Ilham", "Rim", "Amal", "Aya",
  "Laila", "Salima", "Najwa", "Samira", "Jamila", "Abir", "Yasmine", "Oumaima", "Siham", "Ghita",
  "Fadoua", "Safae", "Marwa", "Rita", "Dounia", "Nour", "Ilham", "Ikram", "Sofia", "Meryem"
];
